### ISSUE TITLE
wildcards.py is moved/obsolete

### ISSUE THREAD

**Issue by supernovajm** [Engineer-of-Stuff/stable-diffusion-paperspace#23]
per https://github.com/jtkelm2/stable-diffusion-webui-1/blob/main/scripts/wildcards.py:

> "The old wildcards script is obsolete. Here you'll simply find a (possibly outdated) fork of Adieyal's [Dynamic Prompting script](https://github.com/adieyal/sd-dynamic-prompting), together with my old text files. Adieyal's script performs all the same functions as my old wildcards script and more, so check it out!"

**Comment by Cyberes** [comment]
Fixed in a67f61a4d8ae48cae0b8c68905ab8d14929fa527. Update your notebook please.

**Comment by Tsalnor** [comment]
This is not fixed, there is still a line that tries to download the script.
```
    do_script_download([
        'GRMrGecko/stable-diffusion-webui-automatic/advanced_matrix/scripts/advanced_prompt_matrix.py',
        # 'jtkelm2/stable-diffusion-webui-1/master/scripts/wildcards.py',
        'dfaker/stable-diffusion-webui-cv2-external-masking-script/main/external_masking.py',
        'memes-forever/Stable-diffusion-webui-video/main/videos.py',
        'yownas/seed_travel/main/scripts/seed_travel.py',
        'Animator-Anon/Animator/main/animation.py',
        'Filarius/stable-diffusion-webui/master/scripts/vid2vid.py',
        'GeorgLegato/Txt2Vectorgraphics/main/txt2vectorgfx.py',
        'yownas/shift-attention/main/scripts/shift_attention.py',
        'DiceOwl/StableDiffusionStuff/main/loopback_superimpose.py',
        'Engineer-of-Stuff/stable-diffusion-paperspace/main/lfs/save_steps.py',
        'Pfaeff/sd-web-ui-scripts/main/moisaic.py'
    ], 'raw.githubusercontent.com', f'{repo_storage_dir}/stable-diffusion-webui/scripts/')
```

**Comment by Cyberes** [comment]
Ah, oops. I removed that line but it I must have overwritten that change by accident.
