### ISSUE TITLE
CivitAI Automated Model Downloader

### ISSUE THREAD

**Issue by personxyz** [Engineer-of-Stuff/stable-diffusion-paperspace#53]
Hi,

First up I acknowledge this is almost certainly an issue of my own making, I’m not very technical. 

I was setting things up today on Paperspace and reached the “Automated Model Downloader” cell. My internet sucks so it’s perfect for me but I can’t get it to work

I assumed you added the model URL to the below part (between the colon and the second apostrophe):

model_uri = input(‘URI of model to download: ‘)
import re
import requests
import gdown

However, when I do that and execute the cell a download bar appears but it never actually moves. It’s stuck on zero. 

Do you know what I’m doing wrong? Say I want to download a model from CivitAI. I’ve tried using the model page: https://civitai.com/models/3850/kenshi 

That didn't work so I tried using the download button web link: https://civitai.com/api/download/models/4277 

That didn't work either. Am I placing them in the wrong part of the cell or should the URI I use be something else. It’s so frustrating as I’m one step away from being able to use stable diffusion for the first time!

Any help would be massively appreciated. Like I said, I’m not great with tech so this is likely some rookie mistake on my part.

**Comment by Cyberes** [comment]
No, just run the block. A little textbox will appear below it which is where you put your model URL.

The downloader doesn't support civitai.com right now but maybe I can find the time to add it?

**Comment by personxyz** [comment]
Lol, I'm so dumb. Thanks for the quick response and the tip for downloading from CivitAi. If you do find the time to add civit that would be awesome considering most of the top models get posted on there but no worries if you're busy, you've already made something incredibly useful.

I'll close this issue. Thanks again.

**Comment by Cyberes** [comment]
Great! Glad you got it working. I'll leave the issue open so that I remember to do this.

**Comment by personxyz** [comment]
Hi again, sadly I'm back lol. 

I'm having trouble downloading from huggingface. This time I've attached a screenshot to better illustrate the issue. I ran the cell like you said, entered my huggingface url into the box that appeared and pressed Shift+Enter. All it did was create a blank block underneath (shown in the attached screenshot). 

I've probably messed something up again but can't figure out what. Do you have any ideas?

![paperspace notebook](https://user-images.githubusercontent.com/122485148/212093788-c4c3a4be-38d5-4e43-92bd-2b64bf821fa4.png)

**Comment by Cyberes** [comment]
No, wrong box. You want to run the cell first and then this box will pop up.

![Screenshot 2023-01-12 at 11-24-51 MAIN StableD… - JupyterLab](https://user-images.githubusercontent.com/64224601/212149016-098cab88-bace-42a7-93a8-6928261436da.png)

Your model link goes here.
![Screenshot 2023-01-12 at 11-26-13 MAIN StableD… - JupyterLab](https://user-images.githubusercontent.com/64224601/212149070-49b527ff-e14f-42ef-af65-5ecdd7abd896.png)

**Comment by personxyz** [comment]
Weird, that box doesn't appear for me when I run the block. Maybe I broke it when I was messing around earlier. I might just reinstall the notebook from scratch tomorrow and see if it works then. I'll report back.

**Comment by personxyz** [comment]
OK, I finally worked it out. Because the Automated Model Downloader section is right at the bottom of the notebook I was running it last, after cleaning up and restarting the kernel + linking the models directory. 

I didn't realize you couldn't do things in that order and that's why the model downloader block wouldn't work properly. Like I said, the box in your screenshot never popped up for me. 

I've just tried again and it worked! I'm currently downloading a model from huggingfaces and everything seems to be going smoothly. Apologies for taking some of your time on such a trivial matter but at least it's resolved now.

Thanks again!

**Comment by Cyberes** [comment]
Glad you got it working.

Everything should work after you run the cleanup+kernel restart since the variables are cached in `%store`. I suspect your kernel froze, next time you can try force-restarting it in Kernel > Shutdown all kernels.

**Comment by personxyz** [comment]
Just out of interest, does the Automated Model Downloader work with .safetensor files as well as .ckpt? 

I ask because the "Link the models directory" block doesn't have a section for safetensor files. It only says Link .ckpt files.

**Comment by Cyberes** [comment]
It should. I guess I should update the linker.

**Comment by personxyz** [comment]
I just tried it out of curiosity, when I finished downloading the safetensor file I ran the linking models directory block but nothing new happened. I don't think it recognized the file because it ended in .safetensor. The model didn't load in SD either. 

Who knows though, maybe I've done something wrong again!

**Comment by personxyz** [comment]
I got it to work by adding some more code to the linking models directory block. I basically copied the .ckpt part but replaced each .ckpt with .safetensors (screenshot below).

Miraculously it worked.
![safetensors code](https://user-images.githubusercontent.com/122485148/212377469-b139a86e-0312-4c03-be43-a13ce473cca8.png)

**Comment by Cyberes** [comment]
Nice! That's the right way to do it.

**Comment by Cyberes** [comment]
Closed by https://github.com/Engineer-of-Stuff/stable-diffusion-paperspace/commit/7117369ba1615768d882c0f1af1831159950f2c4 with fixes to CivitAI and .safetensor files.

**Comment by personxyz** [comment]
Hi again,

I thought I'd try out the new Civit download option today but sadly it didn't work. First I updated the notebook and that seemed to work fine as shown by the below screenshot.

![newnotebook](https://user-images.githubusercontent.com/122485148/214620810-645eaa41-c5b6-41a1-91ef-815f11902a37.png)

I refreshed the page but when I tried to download something from Civit I got the following error message.

![civiterror](https://user-images.githubusercontent.com/122485148/214621001-51fce9d7-e000-48f0-bce5-4d146e70ed81.png)

There's definitely a chance the error is my fault but do you have any ideas what went wrong?

**Comment by Cyberes** [comment]
Can I have the link? I got that error earlier and it may be because their backend might be having issues?

**Comment by personxyz** [comment]
Here's the link: https://civitai.com/api/download/models/5848

I don't think it was their backend as I started downloading a model right after I couldn't get the notebook downloader to work. It took 6 hours (because my internet sucks) but it downloaded successfully.

**Comment by Cyberes** [comment]
Their CDN wasn't responding correctly to HEAD requests. Fixed in abca842b30a4317462ca605ae90b709af93baa33.

**Comment by personxyz** [comment]
Hi Cyberes,

Sadly it still doesn't work. I tried it with 4 different Civit models, each time I got the following error (attached as two screenshots due to length).

![ErrorScreenshotOne](https://user-images.githubusercontent.com/122485148/215103912-e22d54e7-08c1-40fb-932e-b45a1189ef1f.png)
![ErrorScreenshotTwo](https://user-images.githubusercontent.com/122485148/215104095-f640f54f-1a69-43cd-afab-2223191da733.png)

**Comment by Cyberes** [comment]
Fixed.

**Comment by personxyz** [comment]
Haven't tested if the Civit downloader works for now as something else has come up. I tried to run the "Launch the WebUI" block and got the following error message: 

![LaunchError](https://user-images.githubusercontent.com/122485148/215184142-d06ee27a-9c9e-4d27-ac52-65e799f97604.png)

Sorry about all these issues dude, I really appreciate your help :)

**Comment by Cyberes** [comment]
Try updating the notebook. The WebUI needs a specific version of PyTorch so I added a line to uninstall it before running the WebUI installer.

**Comment by personxyz** [comment]
Just updated the notebook and it works. I tried the Civit downloader and it works too! Downloaded a 3.9 GB model in 10 seconds, that's absolutely insane compared to my internet speed. 

Thanks so much for the help, another great feature added to an already awesome notebook!

**Comment by Cyberes** [comment]
Great! Glad you got it working.
