### ISSUE TITLE
automated downloader

### ISSUE THREAD

**Issue by brineta** [Engineer-of-Stuff/stable-diffusion-paperspace#92]
Automated downloader no longer working with CivitAi. Giving errors that were not present before. 
![err](https://user-images.githubusercontent.com/130799011/232153762-84b78ff8-f28b-4613-9f9f-d8d682fbf36b.png)

**Comment by Cyberes** [comment]
Yup, civitai changed their website so it isn't working anymore. Lucky for you I just fixed the downloader, I'll push the changes soon.

**Comment by Cyberes** [comment]
Please try 0993272

**Comment by Nierrrrrrr** [comment]
Still not working, same error message.

Edit:
Here's some finding and temporary solution I used.
It's my first time using Automated Model Downloader, so I'm not sure how it used to be, but when I clicked the version of a model in CivitAi, it will give me the URL like "https://civitai.com/models/17362?modelVersionId=24724" which doesn't match the regular expression of civitai_match.

Currently I copy the link on the download button in CivitAi like "https://civitai.com/api/download/models/24724" and use dl_web_file to directly download the models.
